### ISSUE TITLE
an undocumented Y and X property

### ISSUE THREAD

**Issue by ianhobbs** [bly-th/css#10]
Probably others have figured this.

Using this array ( adding more values to the attribute string ) works!!

`  yScale: {
    200: 'var(--space-3xs-2xs) 0',
    300: 'var(--space-2xs-xs) 0',
    400: 'var(--space-xs-s) 0',
    500: 'var(--space-s-m) 0',
    600: 'var(--space-m-l) 0',
    700: 'var(--space-l-xl) 0',
    800: 'var(--space-xl-2xl) 0',
    900: 'var(--space-2xl-3xl) 0',
    1000: 'var(--space-3xl-4xl) 0',
    2000: 'var(--space-4xl-5xl) 0',
  },`

and 

`    'gap-y': {
      items: theme.yScale,
      property: 'margin',
      responsive: true
    },`

love it :)

**Comment by ryangittings** [comment]
Good to hear! v2 is changing the config file to Tailwind, which gives you a bunch of new stuff out of the box, allowing you to use tailwind for tokens only. Pretty powerful!

**Comment by ianhobbs** [comment]
Tell us more about tailwind support.... Currently just importing tokens.css as external file in Tailwind.

**Comment by ryangittings** [comment]
I'll try and update the docs. Basically, you can use any of tailwinds properties, and it'll import these as tokens into your tokens.css file.

**Comment by ryangittings** [comment]
@ianhobbs docs updated!

- https://blythcss.dev/docs/tokens/migration/
- https://blythcss.dev/docs/tokens/
