### ISSUE TITLE
depreciation.

### ISSUE THREAD

**Issue by ianhobbs** [bly-th/css#11]
lots of depreciation  notices using the latest  builds

npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated stringify-package@1.0.1: This module is not used anymore, and has been replaced by @npmcli/package-json
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added

see config.

npm ping                            ok       
npm -v                              ok      current: v9.7.1, latest: v9.7.1
node -v                             ok      current: v18.16.0, recommended: v18.16.0
npm config get registry             ok      using default registry (https://registry.npmjs.org/)

Shall I try an fix it?

**Comment by ryangittings** [comment]
Fixed with [v1.0.5](https://github.com/bly-th/css/releases/tag/v1.0.5).
