### ISSUE TITLE
V1.0.0

### ISSUE THREAD

**Issue by ianhobbs** [bly-th/css#13]
Finding the latest version pretty confusing.
Do you need a standard tailwind setup as well?

**Comment by ryangittings** [comment]
Hi Ian,

If you run `blyth config init`, this will generate the tailwind config file for you. This is where the tokens are now handled (it provides so much out of the box, and with JIT compiling, it has no performance impact).

Tailwind now powers the token generation - that's the significant change here. I've updated the getting started page to show a bit more on how you can use it as part of a dev setup:

https://blythcss.dev/docs/getting-started/

You can still run `blyth tokens` to generate the tokens, too.
