### ISSUE TITLE
Default bash commands are failing

### ISSUE THREAD

**Issue by ianhobbs** [bly-th/css#6]
Default bash commands are failing in M1 mac. Using mac preinstalled node and npm.

**Comment by ryangittings** [comment]
Hey @ianhobbs, can you provide the steps to help me re-create along with the specific errors? I'm running an M1 Mac and it's working here, but let's try and get it sorted for you.

**Comment by ianhobbs** [comment]
gotta be my enviro - i'll go through my node env etc. good to know it's ok on M1

---- enviro -----

node  14.16.1
npm  6.14.12
zsh

Ok it's sorted. Blyth was installed in the project folder.  Installed to  root packages and updated node  / npm etc and it's working fine now.

Thanks @ryangittings
