### ISSUE TITLE
adding variable to css named elements?

### ISSUE THREAD

**Issue by ianhobbs** [bly-th/css#8]
Is there a way of creating alternate themes?

I have standard color theme definitions and export statements. I'd like to add a light and dark  variants of the same color variables.

```
colors: {
    primo: '#FFF0F0',
    stresso: '#EB4563',
    stresso_contra:'#FE5941',
    primo_alt:'#FFF6EC',
    noir: '#373737',
  }
module.exports = {
  theme: theme,
  tokens: {
    color: {
      items: theme.colors,
      property: 'color',
      variable: true,
    },
```

desirable .css

```
.light{--color-primo:#FFF0F0;--color-stresso:#EB4563;--color-stresso_picillo:#F9676E;--color-stresso_contra:#FE5941;--color-primo_alt:#FFF6EC;--color-noir:#373737;}
.dark{--color-primo:#22F0F0;--color-stresso:#EB4223;--color-stresso_picillo:#F2276E;--color-stresso_contra:#FE5941;--color-primo_alt:#FFF6EC;--color-noir:#373737;}
```

? out of scope? Thanks.

**Comment by ryangittings** [comment]
Love this idea, could unlock some cool theming opportunities.

**Comment by ryangittings** [comment]
@ianhobbs Blyth now uses tailwind for design tokens only (this saves manually creating tokens, and allows for optimised CSS files). This means you can write HTML like the TW docs explain (https://tailwindcss.com/docs/dark-mode) or custom CSS with CSS variables.

**Comment by ryangittings** [comment]
@ianhobbs this is now void with Tailwind support, with support baked in:

https://tailwindcss.com/docs/dark-mode
